spring:
  datasource:
    url: jdbc:postgresql://10.178.0.14:5432/postgresql
    username: postgresql
    password: postgrespassword
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  rabbitmq:
    host: 10.178.0.15
    username: buchu
    password: buchu
    port: 5672
server:
  port: 80